spring:
  profiles:
    active: "@activatedProperties@"
    
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate.show_sql: true
      
  datasource:
    url: jdbc:h2:mem:test;
    tomcat:
      max-active: 1
      initial-size: 1    
