name: Build Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

  check-merge-ability:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check if build was successful
      id: check-build
      run: echo "::set-output name=build-successful::$(if [ -z "$GITHUB_REF" ]; then echo 'false'; else echo 'true'; fi)"
    - name: Prevent merge if build failed
      run: |
        if [ "${{ steps.check-build.outputs.build-successful }}" == "false" ]; then
          echo "Build failed. PR cannot be merged."
          exit 1
        fi

