name: Java Maven CI CodeClimate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Install and configure CodeClimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run tests and generate coverage
      run: mvn test

    - name: Upload coverage to CodeClimate
      run: | 
        JACOCO_SOURCE_PATH=/home/runner/work/news-api/news-api/src/main/java ./cc-test-reporter format-coverage /home/runner/work/news-api/news-api/target/site/jacoco/jacoco.xml -d -t jacoco
        ./cc-test-reporter upload-coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
