name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Install and configure CodeClimate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run tests and generate coverage
      run: mvn test

    - name: Upload coverage to CodeClimate
      run: |
        echo "caminho diretorio atual ..."
        pwd
        echo "arquivos diretorio atual ..."
        ls
        echo "check jacoco files..."
        ls target/site/jacoco
        echo "Ajustando permissões..."
        chmod -R 755 target/site/jacoco/
        echo "set jacoco source path ..."
        JACOCO_SOURCE_PATH=news-api/src/main/java ./cc-test-reporter format-coverage ./news-api/target/site/jacoco/jacoco.xml -d -t jacoco
        echo "upload report coverate ..."
        ./cc-test-reporter upload-coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
